### ISSUE TITLE
consoleReader.addTriggerAction dosen't work on Win7

### ISSUE THREAD

**Issue by heroWang** [jline/jline2#116]
i wrote code like this 
addTriggerAction('q', new ActionListener(){ System.exit(0); });
but when i type 'q' while a thread is working,the action was not triggered.
the version i use is jline-2.12-SNAPSHOT.jar

**Comment by gnodet** [comment]
Fixed by https://github.com/jline/jline2/commit/d45b05e25fcc6180ac204963acba1cd662c7430c
