### ISSUE TITLE
ArgumentCompleter only complets on itself

### ISSUE THREAD

**Issue by paulbakker** [jline/jline2#148]
See the following test case: https://github.com/paulbakker/jline2/commit/df91597a72ce74c6c76e57a3a4f3d0080ff1bb94

```
public class MultipleCompleters extends ConsoleReaderTestSupport
{
    @Test
    public void test1() throws Exception {
        console.addCompleter(new StringsCompleter("some", "any"));
        console.addCompleter(new ArgumentCompleter(new StringsCompleter("foo", "bar", "baz")));

        assertBuffer("some foo ", new Buffer("some fo").tab());
    }
}
```

This currently fails.

What I'm trying to do is have a completer to complete a command (the first String completer). Once a command is entered/completed, I want it's arguments to be completed from the second completer. This doesn't work.

It might be that I'm trying something that is not supposed to work. Before I start "fixing" code it would be useful to know if this is intended to work or not.

**Comment by gnodet** [comment]
You need to refactor your code as this is not the way the ArgumentCompleter is supposed to be used.
````
    @Test
    public void test2() throws Exception {
        console.addCompleter(
                new ArgumentCompleter(
                        new StringsCompleter("some", "any"),
                        new StringsCompleter("foo", "bar", "baz")));

        assertBuffer("some foo ", new Buffer("some fo").tab());
    }
````

**Comment by joprice** [comment]
If `ArgumentCompleter` is intended to only work with `StringsCompleter`, which does its constructor accept `Completer`? This seems like a common use case.

**Comment by gnodet** [comment]
This is irrelevant.
The problem is not with the completer passed to ArgumentCompleter, but rather the two calls to addCompleter.  The result is very different, and in that case, not the one that was expected.
The ArgumentCompleter completes multiple tokens, including the command name as the first token to complete, and thus must be given multiple completers, including the one from the command name.

**Comment by joprice** [comment]
Ok. I thought I ran into a similar issue. I'll put together a pr and see if I can replicate it.
