### ISSUE TITLE
clearScreen() on windows doesn't clear ANSI background text color

### ISSUE THREAD

**Issue by bdw429s** [jline/jline2#151]
Using the bleeding edge of Jline on on Windows 7, issuing a clearScreen() call clears the text (which is an improvement over jline1) but any text background colors on the screen from ANSI-formatted output do not get cleared.

Here is a screenshot of what I mean by text with background colors:
http://www.codersrevolution.com/modules/contentbox/content/ANSI_formatting_test.png

And here is what it looks like after clearing the screen:
http://www.codersrevolution.com/modules/contentbox/content/clearScreen.png

**Comment by awayken** [comment]
:+1: I use a project that relies on jline2 to output to the screen. Is there any progress in fixing this bug?

**Comment by gnodet** [comment]
Which terminal / OS are you using when you see this issue ?

**Comment by gnodet** [comment]
Could you also report the output of the `infocmp` command for that terminal...

**Comment by bdw429s** [comment]
The OS was reported in the initial bug (Windows 7).  The terminal is simply cmd.exe.

```
C:\Windows\System32>infocmp
'infocmp' is not recognized as an internal or external command,
operable program or batch file.
```

I don't think Windows supports that command.

**Comment by gnodet** [comment]
I think I know where the problem comes from.
The jansi `WindowsAnsiOutputStream` only clears text but not attributes.

**Comment by awayken** [comment]
@gnodet Has there been any progress on this issue? It looks like you were close to figuring it out.

**Comment by gnodet** [comment]
The fix is in the jansi library, it would require a release of it.
I'll try to look at its status and ping  @chirino  about it ...

**Comment by bdw429s** [comment]
Thanks for the follow up.

**Comment by chirino** [comment]
I just released jansi 1.12

**Comment by awayken** [comment]
Thanks, @gnodet and @chirino!

@bdw429s What does this mean for CommandBox?

**Comment by bdw429s** [comment]
@awayken It means once Jline has a new release with the new jansi lib we can include it.  However, I'm not having much luck this week with the latest version of Jline.  The new enhancement I needed didn't actually work and it introduced two new bugs so I'm probably going to have to revert to an older version of Jline.  We'll have to wait for it all to get fixed before we can try to upgrade again.
