### ISSUE TITLE
Issue with swiss keyboard

### ISSUE THREAD

**Issue by joerupen** [jline/jline2#156]
I am having troubles with certain keys on a swiss-german keyboard. US keyboard layout works (see https://github.com/technomancy/leiningen/issues/1574). Tested on jline-2.13-SNAPSHOT

(On a swiss keyboard you need the ALT+GR key to have access to those keys. maybe that's the cause of this issue.)

@: 

[TRACE] Keystroke: 27
[TRACE] Keystroke: 64

[:
[TRACE] Keystroke: 27
[TRACE] Keystroke: 91

Twice the key [

[TRACE] Keystroke: 27
[TRACE] Keystroke: 91
[TRACE] Keystroke: 27
[TRACE] Keystroke: 91
[TRACE] Binding: SELF_INSERT

]:
prompt> [TRACE] Keystroke: 27
[TRACE] Keystroke: 93

\\: (the backslash key)
[TRACE] Keystroke: 27
[TRACE] Keystroke: 92
[TRACE] Binding: DELETE_HORIZONTAL_SPACE

**Comment by michael72** [comment]
This is (in my opinion) the commit which introduced this bug - anyone can fix it making a distinction between pressing Alt-Key and Alt Gr-Key?
https://github.com/jline/jline2/commit/22b3a2dce329e83a5ecfba137bde404c85954d47

**Comment by winks** [comment]
According to [this comment](https://issues.scala-lang.org/browse/SI-8759?focusedCommentId=71772&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-71772) on the scala bugtracker 2.12.1 might fix it \o/

**Comment by jimbaker** [comment]
It is an issue with Alt-Gr and was reported against a Finnish keyboard layout in this bug for Jython: http://bugs.jython.org/issue2275

I'm still waiting on confirmation that as was seen in Scala (https://issues.scala-lang.org/browse/SI-8759), this fixes the issue.

**Comment by bjornregnell** [comment]
Alt-Gr and [ now works fine on my Swedish keyboard in Scala 2.11.6 which is just released with jLine 2.12.1, available here: http://scala-lang.org/download/

**Comment by jimbaker** [comment]
We now have confirmed that the fix for this issue resolved the problem in Jython, http://bugs.jython.org/issue2275 With the report from @bjornregnell on Scala 2.11.6, this issue is IMHO ready to be closed out as fixed.
