### ISSUE TITLE
Probs with ConsoleRunner

### ISSUE THREAD

**Issue by Gurce** [jline/jline2#157]
Hi,

I was previously using jline1 and running the ConsoleRunner within there (in my case, I was using it to run jdb), and it all worked fine.

But when I tried to do so with jline2 via the following:

/usr/local/jdk1.6.0_29/bin/java -classpath /usr/share/java/jline.jar:/usr/local/jdk1.6.0_29/lib/tools.jar jline.console.internal.ConsoleRunner "com.sun.tools.example.debug.tty.TTY"

I got the following error:

Exception in thread "main" java.lang.IllegalArgumentException: wrong number of arguments
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at jline.console.internal.ConsoleRunner.main(ConsoleRunner.java:77)

By chance, I had downloaded the source for both jline1.0 and jline2.12, so I compared their "ConsoleRunner.java" files and noticed the way they called method.invoke() differed.

So I tried changing jline2 to call method.invoke() in the same fashion as jline1, and now it runs fine:

FROM:

        try {
            Class type = Class.forName(mainClass);
            Method method = type.getMethod("main", new Class[]{String[].class});
            method.invoke(null);
        }
        finally {
            // just in case this main method is called from another program
            ConsoleReaderInputStream.restoreIn();
        }

TO:

        try {
            Class.forName(mainClass).
                getMethod("main", new Class[] { String[].class }).
                invoke(null, new Object[] { argList.toArray(new String[0]) });
        } finally {
            // just in case this main method is called from another program
            ConsoleReaderInputStream.restoreIn();
        }

Just thought it was worth putting on your radar.

**Comment by gnodet** [comment]
Duplicated by #184
