### ISSUE TITLE
Linux bash prompt becomes invisble with jline2 1.12

### ISSUE THREAD

**Issue by tkruse** [jline/jline2#163]
This one breaks the Groovy Shell. To reproduce, in Linux:

create in jline2 project: file src/main/java/jline/example/Main.java
```
package jline.example;

import jline.Terminal;
import jline.TerminalFactory;
import jline.console.ConsoleReader;

public class Main {

    public static void main(final String[] args) throws Exception {
        // creating a terminal AND creating a Reader breaks bash console on exit with jline 1.12
        Terminal term = TerminalFactory.create();
        System.out.println(term.getClass());
        ConsoleReader reader = new ConsoleReader(System.in, System.out);
        // helps if both are called (only when run with mvn java:exec)
        reader.shutdown();
        term.restore();
    }
}
```

Run with:
```
mvn compile
java -classpath /home/kruset/work/java/jline2/target/classes jline.example.Main
```
Note: running with ```mvn java:exec``` instead does not show this symptom (see code comment)!

Tried with Ubuntu, Java7 and Java 8

*With jline 2.11, no such symptom exists.*

git bisect shows:
```
187cc08fe313fd36936899936b9c11559e89a93f is the first bad commit
commit 187cc08fe313fd36936899936b9c11559e89a93f
Author: Ryan Mulligan <ryan@ryantm.com>
Date:   Tue Jan 21 21:21:34 2014 -0800

    preserve stty settings
    
     * saves and restores stty settings instead of overwriting them with
       sane
``` 

Users may call ```reset``` in their bash shell as a workaround, but for that, they'd have to know first.

I am afraid I don't know the best fix for this, nor how to unit-test against this bug. Other projects have similar problems
* http://www.mathworks.com/matlabcentral/answers/96072-why-can-i-not-see-what-i-am-typing-in-the-terminal-after-i-exit-matlab-7-10-r2010a-which-was-start
* http://stackoverflow.com/questions/9557277/how-to-fix-terminal-when-scala-interpreter-causes-invisible-text
* https://github.com/pda/roflbalt/issues/2

**Comment by gnodet** [comment]
I've just pushed a possible fix for this issue.  Can anyone able to reproduce it try the fix ?
  https://github.com/jline/jline2/pull/189
