### ISSUE TITLE
ConsoleReader.print() function does not work unless a prompt is set.

### ISSUE THREAD

**Issue by ghost** [jline/jline2#165]
This is a minor bug, but if I create a new ConsoleReader object, then proceed to call the print(), or println() methods, nothing shows up in the console when the code is executed. If I set a prompt, however, I do see output.

**Comment by gnodet** [comment]
Isn't that just a missing call to flush() ?

**Comment by gnodet** [comment]
Please reopen if this still does not work after calling `ConsoleReader#flush()`
