### ISSUE TITLE
Is it a bug in completion mechanism or not?

### ISSUE THREAD

**Issue by Krasnyanskiy** [jline/jline2#180]
Here is my Java code.
```java
public class CompletionTest {
    public static void main(String[] args) throws IOException {
        ConsoleReader console = new ConsoleReader();
        Completer nil = new NullCompleter();
        Completer read = new StringsCompleter("read");
        Completer and = new StringsCompleter("and");
        Completer save = new StringsCompleter("save");
        Completer aggregator = new AggregateCompleter(
                new ArgumentCompleter(read, and, save, nil)
        );
        console.addCompleter(aggregator);
        while (console.readLine() != null) {
            console.println();
        }
    }
}
```
If I complete an input like in snippet below
```bash
read an[TAB]d
```
and then go back to set the cursor to
```bash
read a[cursor is here]nd
```
and press TAB, I get not expected completion
```bash
read and d
```
Is it a bug or expected behavior of JLine2 library?

**Comment by gnodet** [comment]
The behaviour is supposed to be close to a unix shell.  There may be an additional space printed, but the fact that the completion is done where the cursor is without considering the rest of the line looks correct to me.

**Comment by Krasnyanskiy** [comment]
Yes, right. In Unix we have the same behavior. I found a simple workaround - I just compare buffer length with cursor position and decide to complete the line or skip it.

**Comment by bdw429s** [comment]
I believe the changes for this ticket have caused this regression:
https://github.com/jline/jline2/issues/244
My custom completor never used to output a space at the end of the completion, but now that the logic to add an empty space has been moved from the string completor to the `CandidateListCompletionHandler`, I am getting errant spaces at the end of the completion strings.
