### ISSUE TITLE
drop dependency on oss-parent?

### ISSUE THREAD

**Issue by aklossrbh** [jline/jline2#194]
There's a dependency on oss-parent; does jline actually need that for anything?  If not, it should be removed from the pom.

**Comment by jdillon** [comment]
this provides default configuration needed to deploy to oss.sonatype.org, not really much sense in duplicating that just to avoid setting it as a parent.

**Comment by gnodet** [comment]
Agreed, there's not a ton of stuff in it, but we need to deployment configuration.
