### ISSUE TITLE
cursor position bug in Aggregate Completer

### ISSUE THREAD

**Issue by tkruse** [jline/jline2#208]
Hi,
I notice a regression in JLine2.13 for AggregateCompleter, when the cursor is in the middle of an argument. It is a bit difficult to reproduce right now:
```
List<Completer> completors = new LinkedList<Completer>();
completors.add(
  new ArgumentCompleter(
    new StringsCompleter("foo11", "foo12", "foo13"),
    new StringsCompleter("foo21", "foo22", "foo23")));
```

Then, type these keys exactly, ```|``` indicates cursor position:
```
Type: f, o, o, 1, <left>
Result: foo|1
Type: <tab>
Result: foo11|1
Type: <right>, <backspace>, <backspace>, <left>
Result: foo|1
Type <tab>
Result: foo1o|o
# should be: foo11|1
```

At the end, the cursor cannot go back to delete the first 'f'.

In JLine 2.12.0 and 2.12.1, the behavior is different, with a harmless glitch (additional virtual '1' appears behind the last valid char of the buffer), but else consistent.

Using git bisect, I believe the regression appears with 3b0c474af7b46245 : Support for infocmp capabilities.

**Comment by tkruse** [comment]
I found this using Ubuntu Trusty and Java 1.7.0_80

**Comment by retronym** [comment]
+1

We're seeing this in the Scala REPL with both JLine 2.12.1 and 2.13.

I've spent some time trying to diagnose the problem but didn't make any headway.

**Comment by gnodet** [comment]
Fixed by https://github.com/jline/jline2/commit/8beae1a471aef17e4c721021ea4be3be918da37f

**Comment by retronym** [comment]
Wow, thanks! I've just tested with master and things look good.

Looking forward to 2.13.1. Any idea of likely timeframe for the next release?

**Comment by PascalSchumacher** [comment]
I agree, a  jline2 release containing this fix would be very nice to have.

**Comment by PascalSchumacher** [comment]
Can provide a release with this fix, pretty please?

We would really like to update to JLine 2.13
