### ISSUE TITLE
Does not build with Maven 2

### ISSUE THREAD

**Issue by franslundberg** [jline/jline2#221]
On my computer (Ubuntu 14.04) and Maven 2 (Apache Maven 2.2.1 (rdebian-14)), the suggested

    mvn install

does not work. Error:

    [ERROR] BUILD ERROR
    [INFO] ------------------------------------------------------------------------
    [INFO] Error resolving version for 'org.apache.maven.plugins:maven-shade-plugin': Plugin requires Maven version 3.0

**Comment by jdillon** [comment]
Probably should update the build to require maven3 and update related docs to reflect that.  Not sure its worth trying to fix up the build to keep maven2 compat.

**Comment by franslundberg** [comment]
Just installed Maven 3, it now runs fine.
