### ISSUE TITLE
Jline2 stuck when used in combination with loadwatch

### ISSUE THREAD

**Issue by iMichka** [jline/jline2#230]
Hi

I found a bug in Jython, which uses jline2. See http://bugs.jython.org/issue2412 for more information.
I found out that the bug is in jline2, probably also in jline1. This bug appeared in Jython between version 2.5.1 and 2.5.2, I am not sure which jline version was added at that point. (This was years ago ...)

Consider the following code:

```
import jline.console.ConsoleReader;
import java.io.IOException;

public class Test {

   public static void main(String[] args) {

       try {
           ConsoleReader reader = new ConsoleReader();
       } catch(IOException e) {
           // 
       }
    }
}
```

This works (the script returns and closes):

> /usr/lib/jvm/java-6-openjdk-amd64/bin/javac -classpath "/home/popoff/.m2/repository/jline/jline/2.14-SNAPSHOT/jline-2.14-SNAPSHOT.jar:." Test.java && /usr/lib/jvm/java-6-openjdk-amd64/bin/java -classpath "/home/popoff/.m2/repository/jline/jline/2.14-SNAPSHOT/jline-2.14-SNAPSHOT.jar:." Test

Whit loadwatch `loadwatch -h 10 --`, this does not work (but worked probably in older versions of jline):

> /usr/lib/jvm/java-6-openjdk-amd64/bin/javac -classpath "/home/popoff/.m2/repository/jline/jline/2.14-SNAPSHOT/jline-2.14-SNAPSHOT.jar:." Test.java && loadwatch -h 10 -- /usr/lib/jvm/java-6-openjdk-amd64/bin/java -classpath "/home/popoff/.m2/repository/jline/jline/2.14-SNAPSHOT/jline-2.14-SNAPSHOT.jar:." Test

There, the script is stuck and never returns.

I was able to find out that the code is stuck here:
https://github.com/jline/jline2/blob/master/src/main/java/jline/internal/TerminalLineSettings.java#L331-L333

Could you maybe have a look at this ? I can continue to investigate but was not able to find out what is going on at a first glance.

I am working under Linux (Ubuntu 12.04 and 14.04).

Thanks in advance

**Comment by gnodet** [comment]
I'm not sure loadwatch actually support interactive programs.
I've tried to launch a basic shell with loadwatch without any success.
Could you try to provide a command line with a working interactive program running with loadwatch ?

**Comment by iMichka** [comment]
Not sure what you mean by "interactive program".

I tested:
> echo -e '#!/bin/bash\nread -p "Press any key to continue... " -n1 -s' > test.sh && chmod +x test.sh && $PWD/test.sh

This works as expected.

Then when I do:
> echo -e '#!/bin/bash\nread -p "Press any key to continue... " -n1 -s' > test.sh && chmod +x test.sh && loadwatch -h 10 -- $PWD/test.sh

This never returns / continues, you are not prompted to press any key. The only way to quit is to ctrl-c out of the process. Not sure if this the same problem I am seeing with jline. Though if loadwatch does not work with "interactive programs", how could it work with some older versions of jline 1 at some point.

**Comment by gnodet** [comment]
Exactly, I think loadwatch does not support using the standard streams in the forked processes.  Which kinda makes sense if you consider there is an option to fork the process multiple times.

It seems the problem comes from modifying the tty settings.
See the following output:
```
osboxes@osboxes:/media/sf_gnodet/work/git/jline3$ loadwatch -- sh -c "tty ; stty -g ; stty -a ; echo raw ; stty raw ; stty -g ; stty -a ; stty sane ; echo back"
/dev/pts/19
2102:5:bd:ca3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
speed 9600 baud; rows 40; columns 167; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W;
lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
raw
```

The command hangs when calling `stty raw`...  Fwiw, I've tried with jline3 which can use JNA native calls, and the same happens, i.e. it's stuck when modifying the terminal settings.
In jline2, you could try to force the use of the `UnsupportedTerminal`.

**Comment by gnodet** [comment]
Ok, so i've looked at the `loadwatch` code. It does fork/exec and then call `setpgid(0,0)`, so basically moving the newly created process into the foreground.  When a foreground process tries to read from the terminal, it will block and receive a SIGTTIN interrupt, which suspends it.
So this use case is clearly not supported by `loadwatch`, so I'll close the issue.

**Comment by iMichka** [comment]
Thanks for all the explanations.

So the regression I am seeing was probably introduced by jython itself and not in jline. They are probably not loading the right terminal (Jython with loadwatch works with ```-Dpython.console=org.python.core.PlainConsole```, where a different console is loaded, so the fix is probably to make jython use that other console when working with loadwatch). I will see if I can fix that there. Thanks again.
