### ISSUE TITLE
Please provide a programmatic (public) API to configure logging

### ISSUE THREAD

**Issue by omajid** [jline/jline2#232]
Hi,

jline2 sometimes logs things that are not expected by the users of jline2. Such as exceptions when an event can not be expanded. jline2 provides [an API to modify logging](https://github.com/jline/jline2/wiki/Logging-Configuration) but this API is marked internal. Is there a public/stable API we can use instead to control logging?

**Comment by jerboaa** [comment]
Any update on this? Would you be willing to accept a patch which moves the Log class to a non-internal package? Perhaps best would be to provide a public wrapper for the internal Log class so as to not break old behaviour?

**Comment by gnodet** [comment]
What about the {{jline.log.jul}} ? You can then use the java util logging api to configure the {{jline}} logger.

**Comment by omajid** [comment]
Aha! Yes, that works great for our purposes. Thanks!
