### ISSUE TITLE
Completion handler's unambiguous completion assumes case sensitivity

### ISSUE THREAD

**Issue by bdw429s** [jline/jline2#237]
When there are more than one possible tab completion match, the `getUnambiguousCompletions()` method in `CandidateListCompletionHandler` kicks in to decide how much text is common at the start of each candidate to populate the buffer with as much text as possible.  This comparison is case sensitive which may be fine in some scenarios, but not for all.  An example is file path completion on a Windows system.  

Please see this ticket for CommandBox, a JVM-based CLI that uses JLine. 
https://ortussolutions.atlassian.net/browse/COMMANDBOX-248 

```bash
CommandBox> cd foo  <-- hit tab here
foobar/   Foobar1/
CommandBox> cd  <-- "foo" is erased now
CommandBox> cd foobar <-- Expected to see this
```

As you can see, I take care in my custom completer to match folders of any case (on a Windows system), however the buffer does not keep what I have typed even though it matches both options.  A good precedent is set in Microsoft DOS, where given the same scenario, the best fit is completed, meaning `foobar` is added to the buffer as opposed to nothing.

The offending code that causes this behavior is here (`String.startsWith()`):
https://github.com/jline/jline2/blob/11a3808f302b945d0cc424536299a9c96ccc996f/src/main/java/jline/console/completer/CandidateListCompletionHandler.java#L210

At first I was going to suggest a flag to control this behavior, but after thinking about it-- my completer controls what candidates are passed back and if there are candidates of different cases then that should imply that I do not care about case (or I wouldn't have added them to the List to start with).  Therefore, I think it is safe to make this check not case sensitive all the time since anyone using JLine who needs case-sensitive completion will only add candidates of the same (matching) case which eliminates this situation.

If you approve of this change, I can happily submit a pull request.

**Comment by bdw429s** [comment]
@gnodet Any feedback on this?  I am willing to provide a pull request for the fix and it shouldn't cause issues with any existing implementations.

**Comment by gnodet** [comment]
I'd rather have a flag controlling the behavior, in case some completers are not smart enough, but I have no problems with this change.
Btw, if you want smarter completions, you can have a look at the JLine 3 branch, which includes auto error correction on completion and very nice additional things.

**Comment by bdw429s** [comment]
Thanks for the reply.  Looking forward to Jline 3.  I'll work on converting our CommandBox CLI over to it when it's out.  I'll see if I can get a pull in for this ticket.

**Comment by bdw429s** [comment]
@gnodet Pull created: https://github.com/jline/jline2/pull/249
