### ISSUE TITLE
configurable secondary prompts

### ISSUE THREAD

**Issue by PerBothner** [jline/jline2#246]
Secondary (continuation) prompts should be context-dependent:
- May include a line number.
- Pad to width of primary width, for consistent indentation.
- Padding may be internal (rather than just left or right), and
  not restricted to space.
- May include a short word or indicator (like "quote") to indicate reason
  for a continuation line.

I suggest a printf-style template.  That is simpler to write than a
call-back method hook, and is easier to put in configuration/resource files.
It may also allow optimization.  For example if the prompt does not
contain a %M, then insertSecondaryPrompts doesn't need to call
parser.parse.

I assume secondary prompts may have ANSI escapes, but will ignore that.

A secondary prompt may have these special template markers:

%N -A relative line number. See below.
%M -A short word explaining with is "missing".  This is supplied
    from the EOF missing() method, if provided.  Defaults to an empty string.
%P&lt;_digits_&gt;&lt;_c_&gt;  -Include padding here, repeating following character &lt;_c_&gt;
      as needed to bring the total prompt width as specified by &lt;_digits_&gt;
%P&lt;_c_&gt; -As before, but use width from initial prompt
%% -A literal '%'.

We add to LineReader these methods:

void setLineNumber(int)
int getLineNumber();

%N adds the value from getLineNumber() with the continuation sequence number.
I.e. the first continuation line gets 1 + getLineNumber().

This supports two styles of line numbering:
(1) Command number, followed by line number in command:
  [100] $
  [100.1]&gt; 
  [100.2]&gt;
In that case set the secondary prompt to "[100.%N] &gt;", and
call setLineNumber(0) before calling readLine.
(2) Continuous line numbers:
  [100] $
  [101] &gt; 
  [102] &gt;
In that   case set the secondary prompt to "[%N] &gt;", and
call setLineNumber(100) before calling readLine.

This proposal is a variant with experimental work I've done in DomTerm.
There I've used "#|%P.:%N|#" for Kawa, leading to prompts of the
form "#|...2|# ".  Such a prompt has the form of a comment which
simplifies cut-and-paste.

**Comment by gnodet** [comment]
Sounds good.

**Comment by PerBothner** [comment]
I implemented the above, except that instead of `%P<digits><c>` you write`%<digits>P<c>`/
I also removed the PAD_PROMPTS option as being redundant.

I _think_ I created a pull request, but GitHub seems to show one pull requeest with 2 commits, when I meant that as 2 separate pull requests..  (I'm new to this aspect of GitHub...)

**Comment by gnodet** [comment]
Yeah, that's because you need to create 2 separate branches to create 2 different PRs.

**Comment by PerBothner** [comment]
Could you review them as they are, and possibly pull them as a pair?
Or should I redo the pull requests "properly"?

**Comment by gnodet** [comment]
I can handle them...

**Comment by PerBothner** [comment]
Ping? I'm waiting for these changes to be checked in, so I can check in my changes to Kawa making use of jline3's multi-line editing support (which seems to work pretty good).

**Comment by gnodet** [comment]
I've merged and fixed the PR.

**Comment by PerBothner** [comment]
Thanks - much appreciated.  I've updated Kawa to use the new API.  I'm working on some cleanups (including the public Kawa prompt API) before I check it in.  Once done I'll send a note to dev list so people can see another example of jline3 in action.

I don't understand your changes to expandPromptPattern.  To me they just make the source code longer; the execution slower (useless boxing and unboxing of count); and (I expect) the bytecode bigger.  Am I missing something?

The logic in insertSecondaryPrompts to calculate the padding width seems expensive, since we call parser.parser twice for each line, just so we can pad to the _maximum_ width of all the lines, rather than just the width of the initial line.  That could be desirable, but only if we have a mechanism to also pad out the initial line, which it doesn't appear we do.  It's only a issue if the pattern has both %P and %M, so it's not an issue for me at this point. Later we might consider using a pattern for the initial line as well.

**Comment by gnodet** [comment]
The code was simply not working.  The count variable was set to -1 before being used.  
And yes, the logic can be expensive when computing the maximum, but  I wanted to preserve the original behaviour.
I left prompt expansion out of jline because I'm currently using the following one:
  https://github.com/apache/felix/blob/trunk/gogo/runtime/src/main/java/org/apache/felix/gogo/runtime/Expander.java
The syntax is a subset to zsh parameter expansion syntax (it does not yet support padding), we could also reuse the same syntax for the secondary prompts.

**Comment by PerBothner** [comment]
"The code was simply not working. The count variable was set to -1 before being used."

Oops, that does look wrong.  I could initialize count to -1 outside the loop, but that has problems of its own.

I would still have used an int (initialized to -1) rather than a boxed Integer (initialized to null).

If you want to leave things open to (a subset/superset of) zsh expansion, perhaps we should change some of the letter codes to avoid clashes for zsh. For example, we could change %N to %i.

**Comment by PerBothner** [comment]
The "obvious" way to allow people to "use a different [prompt expansion] syntax if they want" would be to let people override expandPromptPattern.  But LineReader/LineReaderImpl isn't set up to do that. Are you open to the idea of making LineReader a class rather than an interface, and moving the code in LineReaderImpl to LineReader? The way things work now you can't really extend LineReaderImpl (because it is internal), and you can't re-implement LineReader (because it is too big). LineReader is the kind of big API where making it an interface is a pain and gains you nothing.

**Comment by gnodet** [comment]
I'd rather keep interfaces and a clean api. We have a bunch of interfaces for History, Parser, Completer, etc... We can easily add one interface to support such a new requirement.
