### ISSUE TITLE
jline 2.14.1 fails to read single keystrokes under git bash on windows

### ISSUE THREAD

**Issue by radai-rosenblatt** [jline/jline2#259]
im running an application using jline from git bash on windows 7. the application source code does this:

```java
Terminal terminal = TerminalFactory.create();
ConsoleReader reader = new ConsoleReader("whatever", System.in, System.out, terminal);
int read = reader.readCharacter();
```

when run as-is the terminal returned from the factory call is a windows terminal, and it fails to read anything. after CTRL-C is hit and the program exists all the keystrokes typed are passed onto bash (who returns with a "command not found") indicating theyre probably never consumed.

when i try manually creating a UnixTerminal:

```java
Terminal terminal = new UnixTerminal();
terminal.init();
//rest as before
```

the characters are returned (read) only when i hit enter (so i can read lines but not single keystrokes).

git bash version:

```
$ uname -a
MINGW64_NT-6.1 latitude 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys
$ echo $0
/usr/bin/bash
```

**Comment by bdw429s** [comment]
@radai-rosenblatt Please see this ticket which is a possible duplicate:
https://github.com/jline/jline2/issues/245

**Comment by radai-rosenblatt** [comment]
yeah, does look like a dup.

**Comment by bdw429s** [comment]
@radai-rosenblatt To help keep @gnodet 's sanity, you may consider closing this ticket and adding your details to the other one which already has some conversation on it.

**Comment by radai-rosenblatt** [comment]
this is a dup of #245
