### ISSUE TITLE
InfoCmp consumes about 128kb memory

### ISSUE THREAD

**Issue by CodingFabian** [jline/jline2#264]
When looking to reduce memory footprint of karaf, I noticed that InfoCmp consumes 128kb memory. This is mostly held by the NAMES map, which holds all the various permutations.
Could this be maybe restructured or even discarded after startup?

(yes I know. 128kb is not much. But its the third biggest consumer in this karaf runing on a low memory device.)

**Comment by gnodet** [comment]
Could you raise an issue in [jline3](https://github.com/jline/jline3) ?
