### ISSUE TITLE
Remember the currently edited command when navigating through the history

### ISSUE THREAD

**Issue by bdw429s** [jline/jline2#265]
In Bash you can begin entering the command, then use Up key to navigate through the history and Down key to get back up to the command you've been editing. Unfortunately, Jline "forgets" the current command when doing it, so you can only get down to the last executed command. It would be nice to have these things working consistently.

This ticket created from a ticket originally entered for CommandBox, a CFML CLI using JLine: 
https://ortussolutions.atlassian.net/browse/COMMANDBOX-438

**Comment by bdw429s** [comment]
@gnodet Any input on whether this improvement will be considered?

**Comment by gnodet** [comment]
I'd be happy to review any PR you may come up with.

**Comment by gnodet** [comment]
Fwiw, this is already fixed in jline 3

**Comment by bdw429s** [comment]
Thanks @gnodet, I'll look a bit harder at an upgrade path to JLine3.  I don't know what your support matrix is for adding enhancements to old versions, but I'm fine closing this ticket for Jline2 if this is a feature already part of the current iteration of Jline3.
