### ISSUE TITLE
Support for a Comment Character in Jline

### ISSUE THREAD

**Issue by RussellSpitzer** [jline/jline2#271]
We were recently trying to figure out how to support comment characters in JLine. While we are able to parse content after it has been read from ConsoleReader this doesn't let us pre-empt the event Expansion. This means lines like
`#This is a comment!@
`
Will throw an error in the parser prior to the line being given to the client application. 
`java.lang.IllegalArgumentException: !@: event not found
`

It would be useful if JLine could support comments at the interpreter level. Text appearing after an unquoted `#` could be preemptively filtered out of the readLine method.

**Comment by gnodet** [comment]
JLine 3 has a pluggable parser which can support that.
