### ISSUE TITLE
Configure default max history size from inputrc

### ISSUE THREAD

**Issue by timmc** [jline/jline2#277]
Currently FileHistory's max history-size [defaults](https://github.com/jline/jline2/blob/6b1074908f4001026ba923ed64960d9f6c7491ec/src/main/java/jline/console/history/MemoryHistory.java#L28) to 500, which is very low for some applications. It would be great if this could be read from inputrc's config instead.

If I submitted a PR that e.g. pulls this info from ConsoleKeys, would that be welcome?

**Comment by gnodet** [comment]
The default history is a memory only history, unless you use a `ConsoleRunner`.
If you're using a `ConsoleRunner`, it may be more coherent to then use a system property, similar to the `jline.history` one used to define the persistent history location.
But yeah, it could also be configured by the `ConsoleReader` using the config.
I'd happily merge any PR.

**Comment by timmc** [comment]
Ah hmm, I see -- relying code has to create a FileHistory to pass to ConsoleReader in the first place, and it might be odd for MemoryHistory/FileHistory to call into ConsoleReader's .inputrc parsing in order to set a default...

Maybe the better thing to do is to make it easier for relying code to get the inputrc variables. This might mean 1) exposing `ConsoleReader#consoleKeys` directly, 2) exposing a new `ConsoleReader#getVariable` method (name TBD), or 3) making `ConsoleReader#getInputRc` public so that relying code can use the same flow the constructor does:

```java
this.inputrcUrl = getInputRc();
consoleKeys = new ConsoleKeys(this.appName, inputrcUrl);
```

I think I like option 3 the best -- it's the least invasive. I'll play with that.

By the way, I saw in the README after filing this issue that development has ceased on jline2, so I was not expecting a reply here! Glad to hear PRs are still welcome. :-)

**Comment by timmc** [comment]
Bad news: `FileHistory#setMaxSize` doesn't really work, because the constructor calls `load -> internalAdd -> maybeResize`; the data loaded from disk is truncated before the constructor even finishes, so there's no opportunity to set a higher size and preserve that data.

I'll see about adding a constructor argument.

**Comment by timmc-bcov** [comment]
@gnodet How does this PR look?

**Comment by gnodet** [comment]
Looks good to me.  If I haven't merged it by the end of next week, ping again...

**Comment by timmc** [comment]
Thanks! :-D
