### ISSUE TITLE
FilenameCompletor finalizing blank suffix should be optional

### ISSUE THREAD

**Issue by tkruse** [jline/jline2#90]
For groovysh, we'd like to complete

x = '

with filenames, but the trailing blank added by filname Completor is annoying, because the user will in our case likely want to close the hypnens, e.g.:

x = 'foo.txt'

So it would be great if the FilenameCompletor and a construtor option or setter to suppress the blank that is added to file candidates.

**Comment by tkruse** [comment]
I am not sure that a27f3bd fixes the problem. As far as I see, FilenameCOmpleter still adds a blank:
```
CharSequence name = file.getName() + (matches == 1 && file.isDirectory() ? separator() : " ");
```
So making the bank added by the global CompletionHandler does not help much (a little maybe).

I am working on a PR making the FileNameCompleter much more versatile, maybe you can reopen this issue in the meantime.

**Comment by bdw429s** [comment]
Just found this today.  Looks like it fixes https://github.com/jline/jline2/issues/244.
